### PR TITLE
Remove non-existent targets

### PR DESCRIPTION
**Pull request by bas-ie**
One more PR... I could only get the repo to build by commenting out these lines in `application.mk` due to "no rule to make target" for each of them.

### CODE REVIEW

**Comment by bas-ie** [comment]
I'm now noticing your comment in the blog post about hard-coded build paths! I couldn't actually find any of these files (using fzf)... if they do exist but the paths are incorrect, maybe you have more insight as to where they can be found or if they are crucial?

**Comment by polyfractal** [comment]
Ah, actually, I think this was a problem with the `.gitignore`.  One of the definitions was a bit too loose, and was ignoring a valid directory.  Just pushed a change:  76247cfc7a9df9d8851ffb34b1256fb0b6b08760

Would you mind trying again with that new commit?  I have no idea how vital those files are, but they look like they may be at least somewhat important :)

**Comment by bas-ie** [comment]
Oh awesome, willdo when I get home.

**Comment by bas-ie** [comment]
Sorted, but see #3!

**Pull request closed without merging**
